[package]
name = "niiebla"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/niiebla.rs"

[dependencies]
thiserror.workspace = true
byteorder.workspace = true
aes.workspace = true
cbc.workspace = true
