# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

name: "Publish updates of the main documentation to the Docker container registry"

permissions:
  contents: read
  packages: write

# If a new commit is pushed just ignore the current one in the process queue and skip to the newest one
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - "publish/*.*.*/*"

jobs:
  publish-docs-docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.ref_name, 'docs')

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - uses: ./.github/actions/setup-nix
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: ./.github/actions/setup-docker
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"

      - run: dev setup-pnpm
      - run: dev build-docker-static-server docs

      - run: docker push ghcr.io/zelzip/docs:latest
